from pathlib import Path

p = Path('native/src/engine_main.cpp')
s = p.read_text()

def once(old, new):
    global s
    if old not in s:
        raise SystemExit(f'missing integration anchor: {old[:80]!r}')
    if s.count(old) != 1:
        raise SystemExit(f'non-unique integration anchor: {old[:80]!r}')
    s = s.replace(old, new, 1)

once('#include "stageforge/transport_discipline.hpp"\n', '#include "stageforge/transport_discipline.hpp"\n\n#if defined(_WIN32) || defined(__APPLE__)\n#include "engine_control_stdin.h"\n#include "engine_native_audio_command.h"\n#endif\n')
once('    std::array<std::string, kAudioInputSlots> selected_audio_inputs{};\n', '    std::array<std::string, kAudioInputSlots> selected_audio_inputs{};\n#if defined(_WIN32) || defined(__APPLE__)\n    stageforge::EngineNativeAudioRuntime native_audio;\n#endif\n')
once('    std::string line;\n    while (std::getline(std::cin, line)) {\n', '''    std::string line;\n    for (;;) {\n#if defined(_WIN32) || defined(__APPLE__)\n        const auto stdin_wait = stageforge::wait_engine_stdin(20);\n        native_audio.service(0);\n        if (stdin_wait == stageforge::EngineControlWaitResult::timeout) continue;\n        if (stdin_wait == stageforge::EngineControlWaitResult::closed || stdin_wait == stageforge::EngineControlWaitResult::failed) break;\n#endif\n        if (!std::getline(std::cin, line)) break;\n''')
once('            alsa_inputs[slot].close();\n            audio_inputs[slot].enabled.store(false, std::memory_order_release);', '''            alsa_inputs[slot].close();\n#if defined(_WIN32) || defined(__APPLE__)\n            native_audio.close_capture(slot);\n#endif\n            audio_inputs[slot].enabled.store(false, std::memory_order_release);''')
once('            const auto* device = audio_devices.find(selected_audio_inputs[slot]);\n            if (!device || std::string_view(device->backend.data()) != "alsa" || !device->input || !device->connected) {\n                error("unsupported", "selected input has no installed capture adapter"); continue;\n            }\n', '''            const auto* device = audio_devices.find(selected_audio_inputs[slot]);\n#if defined(_WIN32) || defined(__APPLE__)\n            if (device && device->input && device->connected && (std::string_view(device->backend.data()) == "wasapi" || std::string_view(device->backend.data()) == "coreaudio")) {\n                const auto result = stageforge::activate_engine_native_capture(native_audio, slot, device->backend_address.data(), sample_rate, buffer_frames, channels, sample_format, conversion_flags, capture_audio, &audio_inputs[slot]);\n                if (!result.ok) { error("audio", result.error); continue; }\n                audio_inputs[slot].source.store(static_cast<std::uint8_t>(source_index), std::memory_order_release);\n                audio_inputs[slot].sample_rate.store(result.sample_rate_hz, std::memory_order_release);\n                audio_inputs[slot].enabled.store(true, std::memory_order_release);\n                execution_audio_input_backends[slot] = device->backend.data();\n                ok(std::string("slot=") + std::to_string(slot) + " execution=" + execution_audio_input_backends[slot] + " running=1 device=" + selected_audio_inputs[slot] + " source=" + std::to_string(source_index) + " actualRate=" + std::to_string(result.sample_rate_hz) + " actualPeriodFrames=" + std::to_string(result.period_frames) + " actualChannels=" + std::to_string(result.channels) + " actualFormat=" + result.sample_format);\n                continue;\n            }\n#endif\n            if (!device || std::string_view(device->backend.data()) != "alsa" || !device->input || !device->connected) {\n                error("unsupported", "selected input has no installed capture adapter"); continue;\n            }\n''')
once('            audio_inputs[slot].enabled.store(false, std::memory_order_release);\n            alsa_inputs[slot].close();\n            audio_inputs[slot].ring.reset();', '''            audio_inputs[slot].enabled.store(false, std::memory_order_release);\n            alsa_inputs[slot].close();\n#if defined(_WIN32) || defined(__APPLE__)\n            native_audio.close_capture(slot);\n#endif\n            audio_inputs[slot].ring.reset();''')
once('            if (alsa_outputs[slot].status().state == stageforge::AudioDeviceState::running) {\n                error("busy", "audio drift configuration requires stopped output"); continue;\n            }', '''            if (alsa_outputs[slot].status().state == stageforge::AudioDeviceState::running\n#if defined(_WIN32) || defined(__APPLE__)\n                || native_audio.playback_running(slot)\n#endif\n            ) {\n                error("busy", "audio drift configuration requires stopped output"); continue;\n            }''')
once('            alsa_outputs[slot].close();\n            execution_audio_backends[slot] = slot == 0 ? "null-audio" : "none";', '''            alsa_outputs[slot].close();\n#if defined(_WIN32) || defined(__APPLE__)\n            native_audio.close_playback(slot);\n#endif\n            execution_audio_backends[slot] = slot == 0 ? "null-audio" : "none";''')
once('            const auto* device = audio_devices.find(selected_audio_outputs[slot]);\n            if (!device || std::string_view(device->backend.data()) != "alsa" || !device->output || !device->connected) {', '''            const auto* device = audio_devices.find(selected_audio_outputs[slot]);\n#if defined(_WIN32) || defined(__APPLE__)\n            if (device && device->output && device->connected && (std::string_view(device->backend.data()) == "wasapi" || std::string_view(device->backend.data()) == "coreaudio")) {\n                const auto result = stageforge::activate_engine_native_playback(native_audio, slot, device->backend_address.data(), sample_rate, buffer_frames, channels, sample_format, conversion_flags, render_audio, &audio_render_contexts[slot]);\n                if (!result.ok) { for (auto& input : audio_inputs) input.ring.set_reader_active(slot, false); error("audio", result.error); continue; }\n                audio_render_contexts[slot].expected_sample_rate.store(result.sample_rate_hz, std::memory_order_relaxed);\n                execution_audio_backends[slot] = device->backend.data();\n                ok(std::string("slot=") + std::to_string(slot) + " execution=" + execution_audio_backends[slot] + " running=1 device=" + selected_audio_outputs[slot] + " output=" + std::to_string(output_index) + " actualRate=" + std::to_string(result.sample_rate_hz) + " actualPeriodFrames=" + std::to_string(result.period_frames) + " actualChannels=" + std::to_string(result.channels) + " actualFormat=" + result.sample_format);\n                continue;\n            }\n#endif\n            if (!device || std::string_view(device->backend.data()) != "alsa" || !device->output || !device->connected) {''')
# second playback close anchor is deactivate, after activation anchor was consumed above
once('            alsa_outputs[slot].close();\n            execution_audio_backends[slot] = slot == 0 ? "null-audio" : "none";\n            for (auto& input : audio_inputs) input.ring.set_reader_active(slot, false);', '''            alsa_outputs[slot].close();\n#if defined(_WIN32) || defined(__APPLE__)\n            native_audio.close_playback(slot);\n#endif\n            execution_audio_backends[slot] = slot == 0 ? "null-audio" : "none";\n            for (auto& input : audio_inputs) input.ring.set_reader_active(slot, false);''')
once('    artnet_output.close();\n    sacn_output.close();', '''    artnet_output.close();\n    sacn_output.close();\n#if defined(_WIN32) || defined(__APPLE__)\n    native_audio.close();\n#endif''')
p.write_text(s)
